create database high_school_students;

--  create query for portuguese_students table

CREATE TABLE portuguese_students (
    student_id INT NOT NULL,
    school ENUM('GP', 'MS') NOT NULL,
    sex ENUM('M', 'F') NULL,
    age INT(3) NOT NULL,
    CHECK (age >= 15 AND age <= 22),
    address_type ENUM('Urban', 'Rural') NOT NULL,
    family_size ENUM('Less or equal to 3', 'Greater than 3') NULL default null,
    parent_status ENUM('Living together', 'Apart') NULL DEFAULT NULL,
    mother_education ENUM('higher education', 'primary education (4th grade)', 'secondary education', '5th to 9th grade', 'none') NULL default null,
    father_education ENUM('higher education', 'primary education (4th grade)', '5th to 9th grade', 'secondary education', 'none') NULL default null,
    mother_job ENUM('at_home', 'health', 'other', 'services', 'teacher') NULL default null,
    father_job ENUM('teacher', 'other', 'services', 'health', 'at_home') NULL default null,
    school_choice_reason ENUM('course', 'other', 'home', 'reputation') NOT NULL,
    guardian ENUM('mother', 'father', 'other'),
    travel_time ENUM('15 to 30 min.', '<15 min.', '30 min. to 1 hour', '>1 hour'),
    study_time ENUM('2 to 5 hours', '5 to 10 hours', '<2 hours', '>10 hours'),
    class_failures INT(1) NOT NULL,
    CHECK (class_failures >= 0
        AND class_failures <= 4),
    school_support ENUM('yes', 'no') NULL DEFAULT NULL,
    family_support ENUM('yes', 'no') NULL DEFAULT NULL,
    extra_paid_classes ENUM('yes', 'no') NULL DEFAULT NULL,
    activities ENUM('yes', 'no') NULL DEFAULT NULL,
    nursery_school ENUM('yes', 'no') NULL DEFAULT NULL,
    higher_ed ENUM('yes', 'no') NULL DEFAULT NULL,
    internet_access ENUM('yes', 'no') NULL DEFAULT NULL,
    romantic_relationship ENUM('yes', 'no') NULL DEFAULT NULL,
    family_relationship INT(1) NULL DEFAULT NULL,
    CHECK (family_relationship >= 1
        AND family_relationship <= 5),
    free_time INT(1) NULL DEFAULT NULL,
    CHECK (free_time >= 1 AND free_time <= 5),
    social INT(1) NOT NULL,
    CHECK (social >= 1 AND social <= 5),
    weekday_alcohol INT(1) NULL DEFAULT NULL,
    CHECK (weekday_alcohol >= 1
        AND weekday_alcohol <= 5),
    weekend_alcohol INT(1) NULL DEFAULT NULL,
    CHECK (weekend_alcohol >= 1
        AND weekend_alcohol <= 5),
    health INT(1) NULL DEFAULT NULL,
    CHECK (health >= 1 AND health <= 5),
    absences INT(2) NULL DEFAULT NULL,
    CHECK (absences >= 0 AND absences <= 93),
    grade_1 INT(2) NULL DEFAULT NULL,
    CHECK (grade_1 >= 0 AND grade_1 <= 20),
    grade_2 INT(2) NULL DEFAULT NULL,
    CHECK (grade_2 >= 0 AND grade_2 <= 20),
    final_grade INT(2) NULL DEFAULT NULL,
    CHECK (final_grade >= 0 AND final_grade <= 20),
    PRIMARY KEY (student_id)
);

-- create query for math_students table  
CREATE TABLE math_students (
    student_id INT NOT NULL,
    school ENUM('GP', 'MS') NOT NULL,
    sex ENUM('M', 'F') NULL,
    age INT(3) NOT NULL,
    CHECK (age >= 15 AND age <= 22),
    address_type ENUM('Urban', 'Rural') NOT NULL,
    family_size ENUM('Less or equal to 3', 'Greater than 3') NULL default null,
    parent_status ENUM('Living together', 'Apart') NULL DEFAULT NULL,
    mother_education ENUM('higher education', 'primary education (4th grade)', 'secondary education', '5th to 9th grade', 'none') NULL default null,
    father_education ENUM('higher education', 'primary education (4th grade)', '5th to 9th grade', 'secondary education', 'none') NULL default null,
    mother_job ENUM('at_home', 'health', 'other', 'services', 'teacher') NULL default null,
    father_job ENUM('teacher', 'other', 'services', 'health', 'at_home') NULL default null,
    school_choice_reason ENUM('course', 'other', 'home', 'reputation') NOT NULL,
    guardian ENUM('mother', 'father', 'other'),
    travel_time ENUM('15 to 30 min.', '<15 min.', '30 min. to 1 hour', '>1 hour'),
    study_time ENUM('2 to 5 hours', '5 to 10 hours', '<2 hours', '>10 hours'),
    class_failures INT(1) NOT NULL,
    CHECK (class_failures >= 0
        AND class_failures <= 4),
    school_support ENUM('yes', 'no') NULL DEFAULT NULL,
    family_support ENUM('yes', 'no') NULL DEFAULT NULL,
    extra_paid_classes ENUM('yes', 'no') NULL DEFAULT NULL,
    activities ENUM('yes', 'no') NULL DEFAULT NULL,
    nursery_school ENUM('yes', 'no') NULL DEFAULT NULL,
    higher_ed ENUM('yes', 'no') NULL DEFAULT NULL,
    internet_access ENUM('yes', 'no') NULL DEFAULT NULL,
    romantic_relationship ENUM('yes', 'no') NULL DEFAULT NULL,
    family_relationship INT(1) NULL DEFAULT NULL,
    CHECK (family_relationship >= 1
        AND family_relationship <= 5),
    free_time INT(1) NULL DEFAULT NULL,
    CHECK (free_time >= 1 AND free_time <= 5),
    social INT(1) NOT NULL,
    CHECK (social >= 1 AND social <= 5),
    weekday_alcohol INT(1) NULL DEFAULT NULL,
    CHECK (weekday_alcohol >= 1
        AND weekday_alcohol <= 5),
    weekend_alcohol INT(1) NULL DEFAULT NULL,
    CHECK (weekend_alcohol >= 1
        AND weekend_alcohol <= 5),
    health INT(1) NULL DEFAULT NULL,
    CHECK (health >= 1 AND health <= 5),
    absences INT(2) NULL DEFAULT NULL,
    CHECK (absences >= 0 AND absences <= 93),
    grade_1 INT(2) NULL DEFAULT NULL,
    CHECK (grade_1 >= 0 AND grade_1 <= 20),
    grade_2 INT(2) NULL DEFAULT NULL,
    CHECK (grade_2 >= 0 AND grade_2 <= 20),
    final_grade INT(2) NULL DEFAULT NULL,
    CHECK (final_grade >= 0 AND final_grade <= 20),
    PRIMARY KEY (student_id)
);